name: saheli_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.5
  permission_handler: ^9.0.1

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
