name: saheli_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.ubsev

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_google_places_hoc081098: ^1.2.0
  flutter_native_splash: ^2.2.19
  flutter_polyline_points: ^1.0.0
  geolocator: ^9.0.2
  google_api_headers: ^1.5.0+1
  google_maps_flutter: ^2.2.5
  google_maps_webservice: ^0.0.19
  permission_handler: ^9.0.1
  pin_code_fields: ^7.4.0
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  stream_chat_flutter: ^5.3.0
  uuid: ^3.0.7

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_launcher_icons: "^0.12.0"

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/app_icon.jpeg"

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#121212"

  android_12:
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#121212"

  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
